/*
 * Rad Pro
 * FS2011 pin definitions
 *
 * (C) 2022-2024 Gissio
 *
 * License: MIT
 */

#define SYSCLK_FREQUENCY 8000000
#define AHB_FREQUENCY SYSCLK_FREQUENCY
#define APB1_FREQUENCY SYSCLK_FREQUENCY
#define TIM_FREQUENCY SYSCLK_FREQUENCY
#define DEADTIME_TIM_FREQUENCY SYSCLK_FREQUENCY

#define PAYLOAD_BASE 0x08000000
#define PAYLOAD_SIZE (0x8000 - 0x4)

#define PWR_EN_PORT GPIOB
#define PWR_EN_PIN GPIO10
#define PWR_BAT_PORT GPIOA
#define PWR_BAT_PIN GPIO4
#define PWR_BAT_CHANNEL 4
#if defined(STM32F0)
#define PWR_BAT_SCALE_FACTOR 0.5F
#elif defined(STM32F1)
#define PWR_BAT_SCALE_FACTOR 1.0F
#endif
#define PWR_CHRG_PORT GPIOA
#define PWR_CHRG_PIN GPIO5
#define PWR_CHRG_PULLUP
#define PWR_CHRG_ACTIVE_LOW

#define TUBE_HV_PORT GPIOB
#define TUBE_HV_PIN GPIO4
#define TUBE_HV_AF GPIO_AF1
#define TUBE_HV_TIMER_RCC RCC_TIM3
#define TUBE_HV_TIMER TIM3
#define TUBE_HV_TIMER_CCMR TIM_CCMR1
#define TUBE_HV_TIMER_CCMR_MODE TIM_CCMR1_OC1M_PWM1
#define TUBE_HV_TIMER_CCER_CC TIM_CCER_CC1E
#define TUBE_HV_TIMER_CCR TIM_CCR1
#define TUBE_DET_PORT GPIOA
#define TUBE_DET_PIN GPIO6
#define TUBE_DET_PULLUP
#define TUBE_DET_EXTI EXTI6
#if defined(STM32F0)
#define TUBE_DET_EXTI_IRQ NVIC_EXTI4_15_IRQ
#define TUBE_DET_EXTICR_REG SYSCFG_EXTICR3
#define TUBE_DET_EXTICR_VALUE (SYSCFG_EXTICR_GPIOA << (2 * SYSCFG_EXTICR_FIELDSIZE))
#define TUBE_DET_IRQ_HANDLER exti4_15_isr
#define TUBE_DET_TIMER_LOW_RCC RCC_TIM1
#define TUBE_DET_TIMER_LOW TIM1
#define TUBE_DET_TIMER_HIGH_RCC RCC_TIM15
#define TUBE_DET_TIMER_HIGH TIM15
#elif defined(STM32F1)
#define TUBE_DET_EXTI_IRQ NVIC_EXTI9_5_IRQ
#define TUBE_DET_EXTICR_REG AFIO_EXTICR3
#define TUBE_DET_EXTICR_VALUE (0 << (2 * AFIO_EXTICR_FIELDSIZE))
#define TUBE_DET_IRQ_HANDLER exti9_5_isr
#define TUBE_DET_TIMER_LOW_RCC RCC_TIM1
#define TUBE_DET_TIMER_LOW TIM1
#define TUBE_DET_TIMER_HIGH_RCC RCC_TIM4
#define TUBE_DET_TIMER_HIGH TIM4
#endif
#define TUBE_DET2_PORT GPIOA
#define TUBE_DET2_PIN GPIO1

#define KEY_PLAYPAUSE_PORT GPIOB
#define KEY_PLAYPAUSE_PIN GPIO2
#define KEY_MENUOK_PORT GPIOB
#define KEY_MENUOK_PIN GPIO1
#define KEY_UP_PORT GPIOA
#define KEY_UP_PIN GPIO7
#define KEY_DOWN_PORT GPIOB
#define KEY_DOWN_PIN GPIO0
#define KEY_POWER_PORT GPIOB
#define KEY_POWER_PIN GPIO11

#define LCD_RSTB_PORT GPIOB
#define LCD_RSTB_PIN GPIO12
#define LCD_A0_PORT GPIOB
#define LCD_A0_PIN GPIO13
#define LCD_RW_PORT GPIOB
#define LCD_RW_PIN GPIO14
#define LCD_E_PORT GPIOB
#define LCD_E_PIN GPIO15
#define LCD_D0_PORT GPIOA
#define LCD_D0_PIN GPIO8
#define LCD_D1_PORT GPIOA
#define LCD_D1_PIN GPIO9
#define LCD_D2_PORT GPIOA
#define LCD_D2_PIN GPIO10
#define LCD_D3_PORT GPIOA
#define LCD_D3_PIN GPIO11
#define LCD_D4_PORT GPIOA
#define LCD_D4_PIN GPIO12
#if defined(STM32F0)
#define LCD_D5_PORT GPIOF
#define LCD_D5_PIN GPIO6
#define LCD_D6_PORT GPIOF
#define LCD_D6_PIN GPIO7
#elif defined(STM32F1)
#define LCD_D5_PORT GPIOB
#define LCD_D5_PIN GPIO8
#define LCD_D6_PORT GPIOB
#define LCD_D6_PIN GPIO9
#endif
#define LCD_D7_PORT GPIOA
#define LCD_D7_PIN GPIO15
#define LCD_BACKLIGHT_PORT GPIOB
#define LCD_BACKLIGHT_PIN GPIO3
#define LCD_BACKLIGHT_AF GPIO_AF2
#define LCD_BACKLIGHT_TIMER_RCC RCC_TIM2
#define LCD_BACKLIGHT_TIMER TIM2
#define LCD_BACKLIGHT_TIMER_CCMR TIM_CCMR1
#define LCD_BACKLIGHT_TIMER_CCMR_MODE TIM_CCMR1_OC2M_PWM1
#define LCD_BACKLIGHT_TIMER_CCER_CC TIM_CCER_CC2E
#define LCD_BACKLIGHT_TIMER_CCR TIM_CCR2
#define LCD_BACKLIGHT_PWM_FREQUENCY 1000
#define LCD_BACKLIGHT_PWM_PERIOD (TIM_FREQUENCY / LCD_BACKLIGHT_PWM_FREQUENCY)

#define BUZZ_PORT GPIOB
#define BUZZ_PIN GPIO5

#define VIBRATOR_PORT GPIOB
#define VIBRATOR_PIN GPIO6

#define USART_RX_PORT GPIOA
#define USART_RX_PIN GPIO3
#define USART_RX_AF GPIO_AF1
#define USART_TX_PORT GPIOA
#define USART_TX_PIN GPIO2
#define USART_TX_AF GPIO_AF1
#define USART_RCC RCC_USART2
#define USART_INTERFACE USART2
#define USART_IRQ NVIC_USART2_IRQ
#define USART_IRQ_HANDLER usart2_isr
