/*
 * Rad Pro
 * FS2011 specifics
 *
 * (C) 2022-2025 Gissio
 *
 * License: MIT
 */

#include "stm32-ext.h"

#define SYSCLK_FREQUENCY 8000000
#define AHB_FREQUENCY SYSCLK_FREQUENCY
#define APB1_FREQUENCY SYSCLK_FREQUENCY
#define APB2_FREQUENCY SYSCLK_FREQUENCY
#define TIM_FREQUENCY SYSCLK_FREQUENCY
#define LSE_FREQUENCY 32768
#define LSI_FREQUENCY 40000

#define FLASH_SIZE 0x10000
#define FIRMWARE_BASE 0x08000000

#define PWR_EN_PORT GPIOB
#define PWR_EN_PIN 10
#define PWR_BAT_PORT GPIOA
#define PWR_BAT_PIN 4
#define PWR_BAT_CHANNEL 4
#if defined(STM32F0)
#define PWR_BAT_SCALE_FACTOR 0.5F
#elif defined(STM32F1)
#define PWR_BAT_SCALE_FACTOR 1.0F
#endif
#define PWR_BAT_NUM 2.0F
#define PWR_CHRG_PORT GPIOA
#define PWR_CHRG_PIN 5
#define PWR_CHRG_PULLUP
#define PWR_CHRG_ACTIVE_LOW

#define TUBE_HV_PORT GPIOB
#define TUBE_HV_PIN 4
#define TUBE_HV_AF GPIO_AF1
#define TUBE_HV_TIMER TIM3
#define TUBE_HV_TIMER_CHANNEL TIM_CH1
#define TUBE_DET_PORT GPIOA
#define TUBE_DET_PIN 6
#define TUBE_DET_PULLUP
#if defined(STM32F0)
#define TUBE_DET_IRQ EXTI4_15_IRQn
#define TUBE_DET_IRQ_HANDLER EXTI4_15_IRQHandler
#define TUBE_DET_TIMER_MASTER TIM15
#define TUBE_DET_TIMER_SLAVE TIM1
#define TUBE_DET_TIMER_TRIGGER_CONNECTION 0
#elif defined(STM32F1)
#define TUBE_DET_IRQ EXTI9_5_IRQn
#define TUBE_DET_IRQ_HANDLER EXTI9_5_IRQHandler
#define TUBE_DET_TIMER_MASTER TIM4
#define TUBE_DET_TIMER_SLAVE TIM1
#define TUBE_DET_TIMER_TRIGGER_CONNECTION 3
#endif

#define KEY_PLAYPAUSE_PORT GPIOB
#define KEY_PLAYPAUSE_PIN 2
#define KEY_MENUOK_PORT GPIOB
#define KEY_MENUOK_PIN 1
#define KEY_UP_PORT GPIOA
#define KEY_UP_PIN 7
#define KEY_DOWN_PORT GPIOB
#define KEY_DOWN_PIN 0
#define KEY_POWER_PORT GPIOB
#define KEY_POWER_PIN 11

#define BUZZ_PORT GPIOB
#define BUZZ_PIN 5

#define DISPLAY_RSTB_PORT GPIOB
#define DISPLAY_RSTB_PIN 12
#define DISPLAY_A0_PORT GPIOB
#define DISPLAY_A0_PIN 13
#define DISPLAY_RW_PORT GPIOB
#define DISPLAY_RW_PIN 14
#define DISPLAY_E_PORT GPIOB
#define DISPLAY_E_PIN 15
#define DISPLAY_D0_PORT GPIOA
#define DISPLAY_D0_PIN 8
#define DISPLAY_D1_PORT GPIOA
#define DISPLAY_D1_PIN 9
#define DISPLAY_D2_PORT GPIOA
#define DISPLAY_D2_PIN 10
#define DISPLAY_D3_PORT GPIOA
#define DISPLAY_D3_PIN 11
#define DISPLAY_D4_PORT GPIOA
#define DISPLAY_D4_PIN 12
#if defined(STM32F0)
#define DISPLAY_D5_PORT GPIOF
#define DISPLAY_D5_PIN 6
#define DISPLAY_D6_PORT GPIOF
#define DISPLAY_D6_PIN 7
#elif defined(STM32F1)
#define DISPLAY_D5_PORT GPIOB
#define DISPLAY_D5_PIN 8
#define DISPLAY_D6_PORT GPIOB
#define DISPLAY_D6_PIN 9
#endif
#define DISPLAY_D7_PORT GPIOA
#define DISPLAY_D7_PIN 15
#define DISPLAY_BACKLIGHT_PORT GPIOB
#define DISPLAY_BACKLIGHT_PIN 3
#define DISPLAY_BACKLIGHT_AF GPIO_AF2
#define DISPLAY_BACKLIGHT_TIMER TIM2
#define DISPLAY_BACKLIGHT_TIMER_CHANNEL TIM_CH2
#define DISPLAY_BACKLIGHT_TIMER_FREQUENCY 1000
#define DISPLAY_BACKLIGHT_TIMER_PERIOD (TIM_FREQUENCY / DISPLAY_BACKLIGHT_TIMER_FREQUENCY)

#define VIBRATION_PORT GPIOB
#define VIBRATION_PIN 6

#define USART_INTERFACE USART2
#define USART_TX_PORT GPIOA
#define USART_TX_PIN 2
#define USART_TX_AF GPIO_AF1
#define USART_RX_PORT GPIOA
#define USART_RX_PIN 3
#define USART_RX_AF GPIO_AF1
#define USART_APB_FREQUENCY APB1_FREQUENCY
#define USART_IRQ USART2_IRQn
#define USART_IRQ_HANDLER USART2_IRQHandler
