/*
 * Rad Pro
 * Bosean FS-600/FS-1000 specifics
 *
 * (C) 2022-2024 Gissio
 *
 * License: MIT
 */

#include "stm32-ext.h"

#define SYSCLK_FREQUENCY 48000000
#define AHB_FREQUENCY (SYSCLK_FREQUENCY / 2)
#define APB1_FREQUENCY (SYSCLK_FREQUENCY / 2)
#define APB2_FREQUENCY (SYSCLK_FREQUENCY / 2)
#define TIM_FREQUENCY (SYSCLK_FREQUENCY / 2)
#define LSE_FREQUENCY 32768
#define LSI_FREQUENCY 32000

#undef FLASH_SIZE
#define FLASH_SIZE 0x40000
#define FIRMWARE_BASE 0x08000000
#define FIRMWARE_SIZE 0xc000

#define PWR_EN_PORT GPIOA
#define PWR_EN_PIN 11
#define PWR_BAT_PORT GPIOA
#define PWR_BAT_PIN 6
#define PWR_BAT_CHANNEL 6
#define PWR_BAT_SCALE_FACTOR (2.0F / 3.0F)
#define PWR_CHRG_PORT GPIOB
#define PWR_CHRG_PIN 9

#define TUBE_HV_PORT GPIOA
#define TUBE_HV_PIN 4
#define TUBE_HV_AF GPIO_AF4
#define TUBE_HV_TIMER TIM1
#define TUBE_HV_TIMER_CHANNEL TIM_CH1
#define TUBE_DET_PORT GPIOA
#define TUBE_DET_PIN 2
#define TUBE_DET_PULLUP
#define TUBE_DET_IRQ EXTI2_IRQn
#define TUBE_DET_IRQ_HANDLER EXTI2_IRQHandler
#define TUBE_DET_TIMER_MASTER TIM15
#define TUBE_DET_TIMER_SLAVE TIM1
#define TUBE_DET_TIMER_TRIGGER_CONNECTION 0

#define KEY_LEFT_PORT GPIOC
#define KEY_LEFT_PIN 7
#define KEY_RIGHT_PORT GPIOC
#define KEY_RIGHT_PIN 6
#define KEY_SELECT_PORT GPIOB
#define KEY_SELECT_PIN 15

#define BUZZ_PORT GPIOA
#define BUZZ_PIN 10
#define BUZZ_ACTIVE_LOW
#define BUZZ2_PORT GPIOD
#define BUZZ2_PIN 0

#define DISPLAY_RESX_PORT GPIOC
#define DISPLAY_RESX_PIN 5
#define DISPLAY_CSX_PORT GPIOC
#define DISPLAY_CSX_PIN 9
#define DISPLAY_RDX_PORT GPIOC
#define DISPLAY_RDX_PIN 6
#define DISPLAY_WRX_PORT GPIOC
#define DISPLAY_WRX_PIN 7
#define DISPLAY_DCX_PORT GPIOC
#define DISPLAY_DCX_PIN 8
#define DISPLAY_DATA_PORT GPIOB
#define DISPLAY_BACKLIGHT_PORT GPIOB
#define DISPLAY_BACKLIGHT_PIN 0
#define DISPLAY_BACKLIGHT_AF GPIO_AF1
#define DISPLAY_BACKLIGHT_TIMER TIM2
#define DISPLAY_BACKLIGHT_TIMER_CHANNEL TIM_CH3
#define DISPLAY_BACKLIGHT_TIMER_FREQUENCY 1000
#define DISPLAY_BACKLIGHT_TIMER_PERIOD (TIM_FREQUENCY / DISPLAY_BACKLIGHT_TIMER_FREQUENCY)

#define PULSE_LED_PORT GPIOA
#define PULSE_LED_PIN 0
#define PULSE_LED_ACTIVE_LOW

#define VIBRATOR_PORT GPIOA
#define VIBRATOR_PIN 9

#define USART_INTERFACE USART1
#define USART_RX_PORT GPIOB
#define USART_RX_PIN 7
#define USART_RX_AF GPIO_AF0
#define USART_TX_PORT GPIOB
#define USART_TX_PIN 6
#define USART_TX_AF GPIO_AF0
#define USART_APB_FREQUENCY APB2_FREQUENCY
#define USART_IRQ USART1_IRQn
#define USART_IRQ_HANDLER USART1_IRQHandler
