/*
 * Rad Pro
 * Bosean FS-600/FS-1000 pin definitions
 *
 * (C) 2022-2023 Gissio
 *
 * License: MIT
 */

#define PWR_EN_PORT GPIOA
#define PWR_EN_PIN GPIO11

#define PWR_BAT_PORT GPIOA
#define PWR_BAT_PIN GPIO6
#define PWR_BAT_CHANNEL 6
#define PWR_BAT_SCALE_FACTOR (2.0F / 3.0F)

#define PWR_CHRG_PORT GPIOB
#define PWR_CHRG_PIN GPIO9

#define TUBE_HV_PORT GPIOA
#define TUBE_HV_PIN GPIO4
#define TUBE_HV_PORT_SPEED GPIO_OSPEED_VERYHIGH
#define TUBE_HV_AF GPIO_AF4
#define TUBE_HV_TIMER_RCC RCC_TIM14
#define TUBE_HV_TIMER TIM14

#define TUBE_DET_PORT GPIOA
#define TUBE_DET_PIN GPIO2
#define TUBE_DET_EXTI EXTI2
#define TUBE_DET_EXTI_IRQ NVIC_EXTI2_3_IRQ
#define TUBE_DET_IRQ_HANDLER exti2_3_isr

#define TUBE_DET_TIMER_RCC RCC_TIM3
#define TUBE_DET_TIMER TIM3

#define TUBE_DET_TIMER_HIGH TIM15
#define TUBE_DET_TIMER_HIGH_RCC RCC_TIM15

#define KEY_POWER_PORT GPIOB
#define KEY_POWER_PIN GPIO15
#define KEY_ENTER_PORT GPIOC
#define KEY_ENTER_PIN GPIO6
#define KEY_BACK_PORT GPIOC
#define KEY_BACK_PIN GPIO7
#define KEY_UP_PORT GPIOA
#define KEY_UP_PIN GPIO9
#define KEY_DOWN_PORT GPIOA
#define KEY_DOWN_PIN GPIO8

#if defined(PULSE_LED)

#define PULSE_LED_PORT GPIOA
#define PULSE_LED_PIN GPIO0
#define PULSE_LED_ACTIVE_LOW

#endif

#define LCD_RESET_PORT GPIOB
#define LCD_RESET_PIN GPIO2
#define LCD_EN_PORT GPIOB
#define LCD_EN_PIN GPIO1
#define LCD_RS_PORT GPIOB
#define LCD_RS_PIN GPIO10
#define LCD_CLOCK_PORT GPIOB
#define LCD_CLOCK_PIN GPIO11
#define LCD_DATA_PORT GPIOB
#define LCD_DATA_PIN GPIO12
#define LCD_BACKLIGHT_PORT GPIOB
#define LCD_BACKLIGHT_PIN GPIO0

#define BUZZ_PORT GPIOA
#define BUZZ_PIN GPIO10

#define BUZZ_PORT2 GPIOD
#define BUZZ_PIN2 GPIO0

#define BUZZ_ACTIVE_LOW

#define USART_RX_PORT GPIOB
#define USART_RX_PIN GPIO7
#define USART_RX_AF GPIO_AF0

#define USART_TX_PORT GPIOB
#define USART_TX_PIN GPIO6
#define USART_TX_AF GPIO_AF0

#define USART_RCC RCC_USART1
#define USART_INTERFACE USART1
#define USART_IRQ NVIC_USART1_IRQ
#define USART_IRQ_HANDLER usart1_isr
