/*
 * Rad Pro
 * FNIRSI GC-01 driver
 *
 * (C) 2022-2026 Gissio
 *
 * License: MIT
 */

#include "stm32-ext.h"

#define SYSCLK_FREQUENCY 72000000
#define AHB_FREQUENCY (SYSCLK_FREQUENCY / 1)
#define APB1_FREQUENCY (AHB_FREQUENCY / 2)
#define APB1TIM_FREQUENCY (APB1_FREQUENCY * 2)
#define APB2_FREQUENCY (AHB_FREQUENCY / 1)
#define APB2TIM_FREQUENCY (APB2_FREQUENCY * 1)
#define LSE_FREQUENCY 32768
#define LSI_FREQUENCY 40000

#define PWR_EN_PORT GPIOA
#define PWR_EN_PIN 2
#define PWR_BAT_PORT GPIOA
#define PWR_BAT_PIN 0
#define PWR_BAT_CHANNEL 0
#define PWR_BAT_SCALE_FACTOR 2.0F
#define PWR_BAT_NUM 1.0F
#define PWR_CHRGANALOG_PORT GPIOA
#define PWR_CHRGANALOG_PIN 4
#define PWR_CHRGANALOG_CHANNEL 4

#define TUBE_HV_PORT GPIOA
#define TUBE_HV_PIN 3
#define TUBE_HV_TIMER TIM2
#define TUBE_HV_TIMER_CHANNEL TIM_CH4
#define TUBE_HV_FREQUENCY APB1TIM_FREQUENCY
#define TUBE_DET_PORT GPIOC
#define TUBE_DET_PIN 10
#define TUBE_DET_PULLUP
#define TUBE_DET_IRQ EXTI15_10_IRQn
#define TUBE_DET_IRQ_HANDLER EXTI15_10_IRQHandler
#define TUBE_DET_TIMER TIM3
#define TUBE_DET_FREQUENCY APB1TIM_FREQUENCY

#define KEY_LEFT_PORT GPIOC
#define KEY_LEFT_PIN 3
#define KEY_RIGHT_PORT GPIOC
#define KEY_RIGHT_PIN 1
#define KEY_UP_PORT GPIOC
#define KEY_UP_PIN 0
#define KEY_DOWN_PORT GPIOC
#define KEY_DOWN_PIN 2
#define KEY_OK_PORT GPIOA
#define KEY_OK_PIN 1

#define DISPLAY_RESX_PORT GPIOC
#define DISPLAY_RESX_PIN 5
#define DISPLAY_CSX_PORT GPIOC
#define DISPLAY_CSX_PIN 9
#define DISPLAY_DCX_PORT GPIOC
#define DISPLAY_DCX_PIN 8
#define DISPLAY_WRX_PORT GPIOC
#define DISPLAY_WRX_PIN 7
#define DISPLAY_RDX_PORT GPIOC
#define DISPLAY_RDX_PIN 6
#define DISPLAY_DATA_PORT GPIOB
#define DISPLAY_BACKLIGHT_PORT GPIOA
#define DISPLAY_BACKLIGHT_PIN 10
#define DISPLAY_BACKLIGHT_TIMER TIM1
#define DISPLAY_BACKLIGHT_TIMER_CHANNEL TIM_CH3
#define DISPLAY_BACKLIGHT_TIMER_FREQUENCY BUZZER_TIMER_FREQUENCY
#define DISPLAY_BACKLIGHT_TIMER_PERIOD BUZZER_TIMER_PERIOD

#define BUZZER_PORT GPIOA
#define BUZZER_PIN 8
#define BUZZER_TIMER TIM1
#define BUZZER_TIMER_CHANNEL TIM_CH1
#define BUZZER_TIMER_FREQUENCY 2000
#define BUZZER_TIMER_PERIOD (APB2TIM_FREQUENCY / BUZZER_TIMER_FREQUENCY)

#define VIBRATOR_PORT GPIOA
#define VIBRATOR_PIN 9

#define PULSE_LED_PORT GPIOA
#define PULSE_LED_PIN 15

#define USB_INTERFACE USB
#define USB_DM_PORT GPIOA
#define USB_DM_PIN 11
#define USB_DP_PORT GPIOA
#define USB_DP_PIN 12
#define USB_IRQ USB_LP_IRQn
#define USB_IRQ_HANDLER USB_LP_IRQHandler
#define USB_WAKEUP_PIN 18
#define USB_WAKEUP_IRQ OTG_FS_WKUP_IRQn
#define USB_WAKEUP_IRQ_HANDLER OTG_FS_WKUP_IRQHandler
