/*
 * Rad Pro
 * FNIRSI GC-01 pin definitions
 *
 * (C) 2022-2023 Gissio
 *
 * License: MIT
 */

#define PWR_EN_PORT GPIOA
#define PWR_EN_PIN GPIO2

#define PWR_BAT_PORT GPIOA
#define PWR_BAT_PIN GPIO0
#define PWR_BAT_CHANNEL 0
#define PWR_BAT_SCALE_FACTOR 1.0F

#define PWR_CHRG_PORT GPIOA
#define PWR_CHRG_PIN GPIO4

#define TUBE_HV_PORT GPIOA
#define TUBE_HV_PIN GPIO3
#define TUBE_HV_PORT_SPEED GPIO_OSPEED_HIGH
#define TUBE_HV_TIMER_RCC RCC_TIM1
#define TUBE_HV_TIMER TIM1

#define TUBE_DET_PORT GPIOC
#define TUBE_DET_PIN GPIO10
#define TUBE_DET_EXTI EXTI10
#define TUBE_DET_EXTI_IRQ NVIC_EXTI15_10_IRQ
#define TUBE_DET_IRQ_HANDLER exti15_10_isr

#define TUBE_DET_TIMER_RCC RCC_TIM2
#define TUBE_DET_TIMER TIM2

#define TUBE_DET_TIMER_HIGH_RCC RCC_TIM4
#define TUBE_DET_TIMER_HIGH TIM4

#define KEY_POWER_PORT GPIOA
#define KEY_POWER_PIN GPIO1
#define KEY_ENTER_PORT GPIOC
#define KEY_ENTER_PIN GPIO0
#define KEY_BACK_PORT GPIOC
#define KEY_BACK_PIN GPIO1
#define KEY_UP_PORT GPIOC
#define KEY_UP_PIN GPIO2
#define KEY_DOWN_PORT GPIOC
#define KEY_DOWN_PIN GPIO3

#define LCD_PORT_SPEED GPIO_OSPEED_HIGH
#define LCD_RESET_PORT GPIOC
#define LCD_RESET_PIN GPIO5
#define LCD_CS_PORT GPIOC
#define LCD_CS_PIN GPIO6
#define LCD_EN_PORT GPIOC
#define LCD_EN_PIN GPIO7
#define LCD_RS_PORT GPIOC
#define LCD_RS_PIN GPIO8
#define LCD_RW_PORT GPIOC
#define LCD_RW_PIN GPIO9

#define LCD_DATA_PORT GPIOB
#define LCD_DATA_PINS 0xffff

// #define LCD_BACKLIGHT_PORT GPIOB
// #define LCD_BACKLIGHT_PIN GPIO3

#define BUZZ_PORT GPIOC
#define BUZZ_PIN GPIO10
#define BUZZ_ACTIVE_LOW

// #define M_VIB_PORT GPIOB
// #define M_VIB_PIN GPIO6

#define USB_INTERFACE RCC_USB
#define USB_VID 0x0483
#define USB_PID 0x5740
#define USB_DEVICE_RELEASE 0x0200
#define USB_DM_PORT GPIOA
#define USB_DM_PIN GPIO11
#define USB_DP_PORT GPIOA
#define USB_DP_PIN GPIO12
