/*
 * Rad Pro
 * FNIRSI GC-03 driver
 *
 * (C) 2022-2026 Gissio
 *
 * License: MIT
 */

#include "stm32-ext.h"

#define SYSCLK_FREQUENCY 96000000
#define AHB_FREQUENCY (SYSCLK_FREQUENCY / 1)
#define APB1_FREQUENCY (AHB_FREQUENCY / 2)
#define APB1TIM_FREQUENCY (APB1_FREQUENCY * 2)
#define APB2_FREQUENCY (AHB_FREQUENCY / 1)
#define APB2TIM_FREQUENCY (APB2_FREQUENCY * 1)
#define LSE_FREQUENCY 32768
#define LSI_FREQUENCY 40000

#define PWR_EN_PORT GPIOA
#define PWR_EN_PIN 10
#define PWR_BAT_PORT GPIOC
#define PWR_BAT_PIN 0
#define PWR_BAT_CHANNEL 10
#define PWR_BAT_SCALE_FACTOR 2.0F
#define PWR_BAT_NUM 1.0F
#define PWR_USB_PORT GPIOC
#define PWR_USB_PIN 6
#define PWR_USB_PULLUP
#define PWR_USB_ACTIVE_LOW
#define PWR_CHRG_PORT GPIOC
#define PWR_CHRG_PIN 7
#define PWR_CHRG_PULLUP
#define PWR_CHRG_ACTIVE_LOW

#define TUBE_HV_PORT GPIOA
#define TUBE_HV_PIN 2
#define TUBE_HV_TIMER TIM5
#define TUBE_HV_TIMER_CHANNEL TIM_CH3
#define TUBE_HV_FREQUENCY APB1TIM_FREQUENCY
#define TUBE_DET_PORT GPIOA
#define TUBE_DET_PIN 3
#define TUBE_DET_PULLUP
#define TUBE_DET_IRQ EXTI3_IRQn
#define TUBE_DET_IRQ_HANDLER EXTI3_IRQHandler
#define TUBE_DET_TIMER TIM3
#define TUBE_DET_FREQUENCY APB1TIM_FREQUENCY

#define EMFMETER_EN_PORT GPIOB
#define EMFMETER_EN_PIN 14
#define ELECTRIC_FIELD_PORT GPIOC
#define ELECTRIC_FIELD_PIN 2
#define ELECTRIC_FIELD_CHANNEL 12
#define MAGNETIC_FIELD_PORT GPIOC
#define MAGNETIC_FIELD_PIN 3
#define MAGNETIC_FIELD_CHANNEL 13

#define KEY_LEFT_PORT GPIOB
#define KEY_LEFT_PIN 9
#define KEY_RIGHT_PORT GPIOB
#define KEY_RIGHT_PIN 8
#define KEY_POWER_PORT GPIOA
#define KEY_POWER_PIN 9
#define KNOB_A_PORT GPIOB
#define KNOB_A_PIN 5
#define KNOB_B_PORT GPIOB
#define KNOB_B_PIN 7
#define KNOB_IRQ EXTI9_5_IRQn
#define KNOB_IRQ_HANDLER EXTI9_5_IRQHandler

#define DISPLAY_RESX_PORT GPIOC
#define DISPLAY_RESX_PIN 5
#define DISPLAY_CSX_PORT GPIOB
#define DISPLAY_CSX_PIN 0
#define DISPLAY_DCX_PORT GPIOC
#define DISPLAY_DCX_PIN 4
#define DISPLAY_SCL_PORT GPIOA
#define DISPLAY_SCL_PIN 5
#define DISPLAY_SDA_PORT GPIOA
#define DISPLAY_SDA_PIN 7
#define DISPLAY_SPI SPI1
#define DISPLAY_BACKLIGHT_PORT GPIOB
#define DISPLAY_BACKLIGHT_PIN 13
#define DISPLAY_BACKLIGHT_TIMER TIM1
#define DISPLAY_BACKLIGHT_TIMER_CHANNEL TIM_CH1N
#define DISPLAY_BACKLIGHT_TIMER_FREQUENCY BUZZER_TIMER_FREQUENCY
#define DISPLAY_BACKLIGHT_TIMER_PERIOD BUZZER_TIMER_PERIOD

#define BUZZER_PORT GPIOC
#define BUZZER_PIN 11
#define BUZZER_TIMER TIM10
#define BUZZER_TIMER_CHANNEL TIM_CH4
#define BUZZER_TIMER_FREQUENCY 2000
#define BUZZER_TIMER_PERIOD (APB2TIM_FREQUENCY / BUZZER_TIMER_FREQUENCY)

#define VIBRATOR_PORT GPIOB
#define VIBRATOR_PIN 1

#define PULSE_LED_PORT GPIOB
#define PULSE_LED_PIN 15
#define PULSE_LED_ACTIVE_LOW

#define USB_INTERFACE USB
#define USB_DM_PORT GPIOA
#define USB_DM_PIN 11
#define USB_DP_PORT GPIOA
#define USB_DP_PIN 12
#define USB_IRQ USB_LP_IRQn
#define USB_IRQ_HANDLER USB_LP_IRQHandler
#define USB_WAKEUP_PIN 18
#define USB_WAKEUP_IRQ OTG_FS_WKUP_IRQn
#define USB_WAKEUP_IRQ_HANDLER OTG_FS_WKUP_IRQHandler
