/*
 * Rad Pro
 * GQ GMC-800 specifics
 *
 * (C) 2022-2025 Gissio
 *
 * License: MIT
 */

#include "stm32-ext.h"

#define SYSCLK_FREQUENCY 72000000
#define AHB_FREQUENCY (SYSCLK_FREQUENCY / 1)
#define APB1_FREQUENCY (AHB_FREQUENCY / 16)
#define APB1TIM_FREQUENCY (APB1_FREQUENCY * 2)
#define APB2_FREQUENCY (AHB_FREQUENCY / 1)
#define APB2TIM_FREQUENCY (APB2_FREQUENCY * 1)
#define LSE_FREQUENCY 32768
#define LSI_FREQUENCY 40000

#define FLASH_SIZE 0x40000
#define FIRMWARE_BASE 0x08000000

#define PWR_EN_PORT GPIOC
#define PWR_EN_PIN 3
#define PWR_EN_ACTIVE_LOW
#define PWR_BAT_PORT GPIOC
#define PWR_BAT_PIN 4
#define PWR_BAT_CHANNEL 14
#define PWR_BAT_SCALE_FACTOR 2.0F
#define PWR_BAT_NUM 1.0F
#define PWR_USB_PORT GPIOC
#define PWR_USB_PIN 1
#define PWR_CHRG_PORT GPIOB
#define PWR_CHRG_PIN 12
#define PWR_CHRG_PULLUP
#define PWR_CHRG_ACTIVE_LOW

#define TUBE_HV_PORT GPIOB
#define TUBE_HV_PIN 8
#define TUBE_HV_TIMER TIM4
#define TUBE_HV_TIMER_CHANNEL TIM_CH3
#define TUBE_HV_FREQUENCY APB1TIM_FREQUENCY
#define TUBE_DET_PORT GPIOA
#define TUBE_DET_PIN 1
#define TUBE_DET_PULLUP
#define TUBE_DET_IRQ EXTI1_IRQn
#define TUBE_DET_IRQ_HANDLER EXTI1_IRQHandler
#define TUBE_DET_TIMER_MASTER TIM2
#define TUBE_DET_TIMER_SLAVE TIM5
#define TUBE_DET_TIMER_TRIGGER_CONNECTION 0
#define TUBE_DET_FREQUENCY APB1TIM_FREQUENCY

#define KEY_LEFT_PORT GPIOB
#define KEY_LEFT_PIN 15
#define KEY_UP_PORT GPIOB
#define KEY_UP_PIN 14
#define KEY_DOWN_PORT GPIOB
#define KEY_DOWN_PIN 13
#define KEY_RIGHT_PORT GPIOB
#define KEY_RIGHT_PIN 10

#define DISPLAY_RESX_PORT GPIOC
#define DISPLAY_RESX_PIN 6
#define DISPLAY_CSX_PORT GPIOA
#define DISPLAY_CSX_PIN 4
#define DISPLAY_DCX_PORT GPIOB
#define DISPLAY_DCX_PIN 11
#define DISPLAY_SCL_PORT GPIOA
#define DISPLAY_SCL_PIN 5
#define DISPLAY_SDA_PORT GPIOA
#define DISPLAY_SDA_PIN 7
#define DISPLAY_BACKLIGHT_PORT GPIOB
#define DISPLAY_BACKLIGHT_PIN 0
#define DISPLAY_BACKLIGHT_TIMER TIM3
#define DISPLAY_BACKLIGHT_TIMER_CHANNEL TIM_CH3
#define DISPLAY_BACKLIGHT_TIMER_FREQUENCY 1000
#define DISPLAY_BACKLIGHT_TIMER_PERIOD (APB1TIM_FREQUENCY / DISPLAY_BACKLIGHT_TIMER_FREQUENCY)

#define SOUND_EN_PORT GPIOB
#define SOUND_EN_PIN 1
#define PULSE_LED_PORT GPIOB
#define PULSE_LED_PIN 3
#define ALERT_LED_PORT GPIOB
#define ALERT_LED_PIN 4

#define VOICE_TX_PORT GPIOA
#define VOICE_TX_PIN 2
#define VOICE_TX_TIMER TIM6
#define VOICE_TX_TIMER_FREQUENCY 5000
#define VOICE_TX_TIMER_PERIOD (APB1TIM_FREQUENCY / VOICE_TX_TIMER_FREQUENCY)
#define VOICE_TX_DMA DMA2
#define VOICE_TX_DMA_CHANNEL DMA2_Channel3
#define VOICE_BUSY_PORT GPIOA
#define VOICE_BUSY_PIN 3
#define VOICE_PROG_PORT GPIOB
#define VOICE_PROG_PIN 6

#define VIBRATION_PORT GPIOB
#define VIBRATION_PIN 5

#define USART_INTERFACE USART1
#define USART_TX_PORT GPIOA
#define USART_TX_PIN 9
#define USART_RX_PORT GPIOA
#define USART_RX_PIN 10
#define USART_APB_FREQUENCY APB2_FREQUENCY
#define USART_IRQ USART1_IRQn
#define USART_IRQ_HANDLER USART1_IRQHandler

#define SYSTEM_RESET_EN_PORT GPIOC
#define SYSTEM_RESET_EN_PIN 0
#define SYSTEM_BOOT0_PORT GPIOD
#define SYSTEM_BOOT0_PIN 2
