/*
 * Rad Pro
 * Settings
 *
 * (C) 2022-2024 Gissio
 *
 * License: MIT
 */

#if !defined(SETTINGS_H)
#define SETTINGS_H

#include <stdint.h>

#include "menu.h"
#include "view.h"

typedef struct
{
    uint32_t time;
    uint32_t pulseCount;
} Dose;

enum
{
    UNITS_SIEVERTS,
    UNITS_REM,
    UNITS_CPM,
    UNITS_CPS,

    UNITS_NUM,
};

enum
{
    AVERAGETIMER_UNLIMITED,
    AVERAGETIMER_5M,
    AVERAGETIMER_10M,
    AVERAGETIMER_30M,
    AVERAGETIMER_60M,

    AVERAGETIMER_NUM,
};

enum
{
    RATEALARM_OFF,
    RATEALARM_0_5,
    RATEALARM_1,
    RATEALARM_2,
    RATEALARM_5,
    RATEALARM_10,
    RATEALARM_20,
    RATEALARM_50,
    RATEALARM_100,

    RATEALARM_NUM,
};

enum
{
    DOSEALARM_OFF,
    DOSEALARM_5,
    DOSEALARM_10,
    DOSEALARM_20,
    DOSEALARM_50,
    DOSEALARM_100,
    DOSEALARM_200,
    DOSEALARM_500,
    DOSEALARM_1000,

    DOSEALARM_NUM,
};

enum
{
    DATALOGGING_OFF,
    DATALOGGING_60M,
    DATALOGGING_30M,
    DATALOGGING_10M,
    DATALOGGING_5M,
    DATALOGGING_1M,

    DATALOGGING_NUM,
};

enum
{
    TUBE_CONVERSIONFACTOR_HH614,
    TUBE_CONVERSIONFACTOR_J305,
    TUBE_CONVERSIONFACTOR_J321,
    TUBE_CONVERSIONFACTOR_J614,
    TUBE_CONVERSIONFACTOR_M4011,
    TUBE_CONVERSIONFACTOR_SBM20,

    TUBE_CONVERSIONFACTOR_NUM,
};

#if defined(SDLSIM)

#define TUBE_CONVERSIONFACTOR_DEFAULT TUBE_CONVERSIONFACTOR_M4011

#define TUBE_FACTORYDEFAULT_HVFREQUENCY TUBE_PWMFREQUENCY_2_5
#define TUBE_FACTORYDEFAULT_HVDUTYCYCLE_PERMILLE 100

#define TUBE_OPTIMIZED_HVFREQUENCY TUBE_PWMFREQUENCY_2_5
#define TUBE_OPTIMIZED_HVDUTYCYCLE_PERMILLE 100

#define TUBE_ENERGYSAVING_HVFREQUENCY TUBE_PWMFREQUENCY_2_5
#define TUBE_ENERGYSAVING_HVDUTYCYCLE_PERMILLE 100

#elif defined(FS2011) || defined(FS600) || defined(FS1000)

#define TUBE_CONVERSIONFACTOR_DEFAULT TUBE_CONVERSIONFACTOR_HH614

#define TUBE_FACTORYDEFAULT_HVFREQUENCY TUBE_PWMFREQUENCY_40
#define TUBE_FACTORYDEFAULT_HVDUTYCYCLE_PERMILLE 500

#define TUBE_OPTIMIZED_HVFREQUENCY TUBE_PWMFREQUENCY_2_5
#define TUBE_OPTIMIZED_HVDUTYCYCLE_PERMILLE 65

#define TUBE_ENERGYSAVING_HVFREQUENCY TUBE_PWMFREQUENCY_2_5
#define TUBE_ENERGYSAVING_HVDUTYCYCLE_PERMILLE 30

#elif defined(GC01)

#define TUBE_CONVERSIONFACTOR_DEFAULT TUBE_CONVERSIONFACTOR_J321

#define TUBE_FACTORYDEFAULT_HVFREQUENCY TUBE_PWMFREQUENCY_10
#define TUBE_FACTORYDEFAULT_HVDUTYCYCLE_PERMILLE 200

#define TUBE_OPTIMIZED_HVFREQUENCY TUBE_PWMFREQUENCY_10
#define TUBE_OPTIMIZED_HVDUTYCYCLE_PERMILLE 200

#define TUBE_ENERGYSAVING_HVFREQUENCY TUBE_PWMFREQUENCY_10
#define TUBE_ENERGYSAVING_HVDUTYCYCLE_PERMILLE 200

#endif

#define GET_HVDUTYCYCLE(permille) ((500 - permille) * TUBE_PWMDUTYCYCLE_NUM / 500)

#define TUBE_FACTORYDEFAULT_HVDUTYCYCLE GET_HVDUTYCYCLE(TUBE_FACTORYDEFAULT_HVDUTYCYCLE_PERMILLE)
#define TUBE_OPTIMIZED_HVDUTYCYCLE GET_HVDUTYCYCLE(TUBE_OPTIMIZED_HVDUTYCYCLE_PERMILLE)
#define TUBE_ENERGYSAVING_HVDUTYCYCLE GET_HVDUTYCYCLE(TUBE_ENERGYSAVING_HVDUTYCYCLE_PERMILLE)

enum
{
    TUBE_HVPROFILE_FACTORY_DEFAULT,
    TUBE_HVPROFILE_OPTIMIZED,
    TUBE_HVPROFILE_ENERGY_SAVING,
    TUBE_HVPROFILE_CUSTOM,
    TUBE_HVPROFILE_NUM,
};

enum
{
    TUBE_PWMFREQUENCY_1_25,
    TUBE_PWMFREQUENCY_2_5,
    TUBE_PWMFREQUENCY_5,
    TUBE_PWMFREQUENCY_10,
    TUBE_PWMFREQUENCY_20,
    TUBE_PWMFREQUENCY_40,
    TUBE_PWMFREQUENCY_NUM,
};

#define TUBE_PWMDUTYCYCLE_NUM 200

#if defined(PULSE_LED)
enum
{
    PULSE_LED_OFF,
    PULSE_LED_ON,

    PULSE_LED_NUM,
};
#endif

enum
{
    PULSE_CLICKS_OFF,
    PULSE_CLICKS_QUIET,
    PULSE_CLICKS_LOUD,

    PULSE_CLICKS_NUM,
};

#if defined(DISPLAY_MONOCHROME)

#define DISPLAY_CONTRAST_DEFAULT 4
#define DISPLAY_CONTRAST_NUM 8

#elif defined(DISPLAY_COLOR)

enum
{
    DISPLAY_THEME_DAY,
    DISPLAY_THEME_DUSK,
    DISPLAY_THEME_NIGHT,

    DISPLAY_THEME_NUM,
};

#endif

enum
{
#if defined(DISPLAY_MONOCHROME)
    DISPLAY_SLEEP_ALWAYS_OFF,
#endif
    DISPLAY_SLEEP_30S,
    DISPLAY_SLEEP_1M,
    DISPLAY_SLEEP_2M,
    DISPLAY_SLEEP_5M,
#if defined(DISPLAY_MONOCHROME)
    DISPLAY_SLEEP_PULSE_FLASHES,
#endif
    DISPLAY_SLEEP_ALWAYS_ON,

    DISPLAY_SLEEP_NUM,
};

enum
{
    DISPLAY_BRIGHTNESS_LOW,
    DISPLAY_BRIGHTNESS_MEDIUM,
    DISPLAY_BRIGHTNESS_HIGH,
    DISPLAY_BRIGHTNESS_VERYHIGH,

    DISPLAY_BRIGHTNESS_NUM,
};

enum
{
    RTC_TIMEZONE_N1200,
    RTC_TIMEZONE_N1100,
    RTC_TIMEZONE_N1000,
    RTC_TIMEZONE_N0900,
    RTC_TIMEZONE_N0800,
    RTC_TIMEZONE_N0700,
    RTC_TIMEZONE_N0600,
    RTC_TIMEZONE_N0500,
    RTC_TIMEZONE_N0400,
    RTC_TIMEZONE_N0300,
    RTC_TIMEZONE_N0200,
    RTC_TIMEZONE_N0100,
    RTC_TIMEZONE_P0000,
    RTC_TIMEZONE_P0100,
    RTC_TIMEZONE_P0200,
    RTC_TIMEZONE_P0300,
    RTC_TIMEZONE_P0400,
    RTC_TIMEZONE_P0500,
    RTC_TIMEZONE_P0600,
    RTC_TIMEZONE_P0700,
    RTC_TIMEZONE_P0800,
    RTC_TIMEZONE_P0900,
    RTC_TIMEZONE_P1000,
    RTC_TIMEZONE_P1100,
    RTC_TIMEZONE_P1200,
    RTC_TIMEZONE_P1300,
    RTC_TIMEZONE_P1400,

    RTC_TIMEZONE_NUM,
};

#if defined(BATTERY_REMOVABLE)
enum
{
    BATTERYTYPE_NI_MH,
    BATTERYTYPE_ALKALINE,

    BATTERYTYPE_NUM,
};
#endif

enum
{
    GAMESTRENGTH_1,
    GAMESTRENGTH_2,
    GAMESTRENGTH_3,
    GAMESTRENGTH_4,
    GAMESTRENGTH_5,
    GAMESTRENGTH_6,
    GAMESTRENGTH_7,
    GAMESTRENGTH_8,

    GAMESTRENGTH_NUM,
};

typedef struct
{
    unsigned int entryEmpty : 1;

    unsigned int units : 2;
    unsigned int averageTimer : 3;
    unsigned int rateAlarm : 4;
    unsigned int doseAlarm : 4;
    unsigned int datalogInterval : 3;
    unsigned int tubeConversionFactor : 7;
    unsigned int tubeDeadTimeCompensation : 6;
    unsigned int tubeHVProfile : 2;
    unsigned int tubePWMFrequency : 3;
    unsigned int tubePWMDutyCycle : 8;

#if defined(PULSE_LED)
    unsigned int pulseLED : 1;
#endif
    unsigned int pulseClicks : 2;
#if defined (DISPLAY_MONOCHROME)
    unsigned int displayContrast : 3;
#elif defined(DISPLAY_COLOR)
    unsigned int displayTheme : 2;
#endif
    unsigned int displaySleep : 3;
    unsigned int displayBrightness : 2;
    unsigned int rtcTimeZone : 5;
#if defined(BATTERY_REMOVABLE)
    unsigned int batteryType : 1;
#endif

    unsigned int gameStrength : 3;
} Settings;

extern Settings settings;

extern const View settingsMenuView;

void initSettings(void);

void writeSettings(void);

void onSettingsSubMenuBack(const Menu *menu);

#endif
