#!/bin/sh

./fontconv.exe -a 6 -s '0x20-0x7e,0xb1,0xb5' Tiny5-Regular.bdf ../platform.io/src/fonts/font_Tiny5.h
./fontconv.exe -s '0x20,0x25,0x28-0x29,0x2b,0x2d-0x3a,0x3f,0x41-0x5a,0x61-0x7a,0x80-0x81,0xb1,0xb5' RadPro-Sans8.bdf ../platform.io/src/fonts/font_RadProSans8.h
./fontconv.exe -s '0x2e,0x30-0x39,0x7f' OpenSans-SemiBold33-Digits.bdf ../platform.io/src/fonts/font_OpenSansSemiBold33_digits.h
./fontconv.exe -s '0x30-0x3c' RadPro-Symbols8.bdf ../platform.io/src/fonts/font_RadProSymbols8.h
./fontconv.exe -s '0x40-0x56' RadPro-Chess8.bdf ../platform.io/src/fonts/font_RadProChess8.h

./fontconv.exe -b 2 -p 17 -c 12 -a 17 -s '0x20-0x7e,0xb1,0xb5' OpenSans-MediumRadPro.ttf ../platform.io/src/fonts/font_OpenSansMedium12_2.h
./fontconv.exe -b 2 -p 25 -c 18 -a 25 -s '0x20,0x25,0x28-0x29,0x2b,0x2d-0x3a,0x3f,0x41-0x5a,0x61-0x7a,0x80-0x81,0xb1,0xb5' OpenSans-MediumRadPro.ttf ../platform.io/src/fonts/font_OpenSansMedium18_2.h
./fontconv.exe -b 2 -p 118 -c 86 -a 113 -s '0x2e,0x30-0x39,0x7f' OpenSans-SemiBoldRadPro.ttf ../platform.io/src/fonts/font_OpenSansSemiBold86_digits_2.h
./fontconv.exe -b 2 -p 86 -c 63 -a 83 -s '0x2e,0x30-0x39,0x7f' OpenSans-SemiBoldRadPro.ttf ../platform.io/src/fonts/font_OpenSansSemiBold63_digits_2.h
./fontconv.exe -b 2 -p 24 -s '0x30-0x3c' MaterialSymbols-RadPro.ttf ../platform.io/src/fonts/font_MaterialSymbols_RadPro_2.h
./fontconv.exe -b 2 -p 24 -s '0x30-0x34,0x3a-0x3c' MaterialSymbols-RadPro.ttf ../platform.io/src/fonts/font_MaterialSymbols_RadPro_nocharging_2.h
./fontconv.exe -b 2 -p 25 -s '0x40-0x47' FreeSerif-ChessRadPro.ttf ../platform.io/src/fonts/font_FreeSansChess25_2.h

./fontconv.exe -b 4 -p 17 -c 12 -a 17 -s '0x20-0x7e,0xb1,0xb5' OpenSans-MediumRadPro.ttf ../platform.io/src/fonts/font_OpenSansMedium12.h
./fontconv.exe -b 4 -p 25 -c 18 -a 25 -s '0x20,0x25,0x28-0x29,0x2b,0x2d-0x3a,0x3f,0x41-0x5a,0x61-0x7a,0x80-0x81,0xb1,0xb5' OpenSans-MediumRadPro.ttf ../platform.io/src/fonts/font_OpenSansMedium18.h
./fontconv.exe -b 4 -p 118 -c 86  -a 113 -s '0x2e,0x30-0x39,0x7f' OpenSans-SemiBoldRadPro.ttf ../platform.io/src/fonts/font_OpenSansSemiBold86_digits.h
./fontconv.exe -b 4 -p 86 -c 63 -a 83 -s '0x2e,0x30-0x39,0x7f' OpenSans-SemiBoldRadPro.ttf ../platform.io/src/fonts/font_OpenSansSemiBold63_digits.h
./fontconv.exe -b 4 -p 24 -s '0x30-0x3c' MaterialSymbols-RadPro.ttf ../platform.io/src/fonts/font_MaterialSymbols_RadPro.h
./fontconv.exe -b 4 -p 24 -s '0x30-0x34,0x3a-0x3c' MaterialSymbols-RadPro.ttf ../platform.io/src/fonts/font_MaterialSymbols_RadPro_nocharging.h
./fontconv.exe -b 4 -p 25 -s '0x40-0x47' FreeSerif-ChessRadPro.ttf ../platform.io/src/fonts/font_FreeSansChess25.h
