#!/bin/sh
../../../tools/u8g2-2.29.11/tools/font/bdfconv/bdfconv.exe -v -f 1 -m '32-127' font_tiny5.bdf -o ../cubeide/Core/fs2011pro/resources/font_tiny5.h -n font_tiny5
../../../tools/u8g2-2.29.11/tools/font/bdfconv/bdfconv.exe -v -f 1 -m '32-127' font_helvR08.bdf -o ../cubeide/Core/fs2011pro/resources/font_helvR08.h -n font_helvR08
../../../tools/u8g2-2.29.11/tools/font/bdfconv/bdfconv.exe -v -f 1 -m '45-57' font_helvR24.bdf -o ../cubeide/Core/fs2011pro/resources/font_helvR24.h -n font_helvR24
../../../tools/u8g2-2.29.11/tools/font/bdfconv/bdfconv.exe -v -f 1 -m '48-111' font_icons.bdf -o ../cubeide/Core/fs2011pro/resources/font_icons.h -n font_icons
