#!/bin/bash

# Builds Rad Pro fonts
#
# NOTES:
# * Open Sans has an em-square to cap height ratio of 1.4
# * Noto Sans has an em-square to cap height ratio of 1.3568
# * When changing the large font, make sure Figure Dash (U+2012) is available.
# * When changing fonts, make sure the `displayTextbuffer` variable is large enough for the font.

# Create and activate virtual environment

VENV_DIR="venv"

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"

    source "$VENV_DIR/bin/activate"

    pip install bdflib freetype-py

else
    source "$VENV_DIR/bin/activate"
fi

# Codepoint sets

CODEPOINT_SET_LARGE=0x2e,0x30-0x39,0x2012
CODEPOINT_SET_MONO_SYMBOLS=0x30-0x3e,0x41-0x46,0x49-0x4e,0x51-0x56
CODEPOINT_SET_COLOR_SYMBOLS=0x30-0x3e,0x41-0x46
CODEPOINT_SET_COLOR_NOCHARGING_SYMBOLS=0x30-0x34,0x3a-0x3e,0x41-0x46
CODEPOINT_SET_COLOR_LOW_SYMBOLS=0x30-0x34,0x3a-0x3e

# Common

python fontconv.py -s $CODEPOINT_SET_LARGE -n font_large "../fonts/RadPro-Sans33-Digits.bdf" "../platform.io/src/fonts/font_mono_large.h"
python fontconv.py -s $CODEPOINT_SET_LARGE -p 118 -b 4 -a 113 -c 86 -n font_large "../fonts/OpenSans-SemiBoldFigureDash.ttf" "../platform.io/src/fonts/font_color_large.h"
python fontconv.py -s $CODEPOINT_SET_LARGE -p 86 -b 4 -a 83 -c 63 -n font_large "../fonts/OpenSans-SemiBoldFigureDash.ttf" "../platform.io/src/fonts/font_color_large_portrait.h"
python fontconv.py -s $CODEPOINT_SET_LARGE -p 118 -b 2 -a 113 -c 86 -n font_large "../fonts/OpenSans-SemiBoldFigureDash.ttf" "../platform.io/src/fonts/font_color_low_large.h"

python fontconv.py -s $CODEPOINT_SET_MONO_SYMBOLS -n font_symbols "../fonts/RadPro-Symbols8.bdf" "../platform.io/src/fonts/font_mono_symbols.h"
python fontconv.py -s $CODEPOINT_SET_COLOR_SYMBOLS -p 24 -b 4 -n font_symbols "../fonts/RadPro-Symbols.ttf" "../platform.io/src/fonts/font_color_symbols.h"
python fontconv.py -s $CODEPOINT_SET_COLOR_NOCHARGING_SYMBOLS -p 24 -b 4 -n font_symbols "../fonts/RadPro-Symbols.ttf" "../platform.io/src/fonts/font_color_nocharging_symbols.h"
python fontconv.py -s $CODEPOINT_SET_COLOR_LOW_SYMBOLS -p 24 -b 2 -n font_symbols "../fonts/RadPro-Symbols.ttf" "../platform.io/src/fonts/font_color_low_symbols.h"

# Languages

for LANGUAGE_FILE in ../platform.io/src/strings/*.h; do
    LANGUAGE=`basename $LANGUAGE_FILE .h`

    CODEPOINT_SET_SMALL=`python textproc.py -c -s 0x20-0x7e ../platform.io/src/strings/$LANGUAGE.h`
    CODEPOINT_SET_MEDIUM=`python textproc.py -c ../platform.io/src/strings/$LANGUAGE.h`

    if [[ "$LANGUAGE" == "ja" ]]; then
        FONT_MONO_SMALL="../fonts/QuanPixel-7.bdf"
        FONT_MONO_MEDIUM="../fonts/FusionPixel-12.bdf"
        FONT_COLOR="../fonts/NotoSansJP-Medium.ttf"
    elif [[ "$LANGUAGE" == "ko" ]]; then
        FONT_MONO_SMALL="../fonts/QuanPixel-7.bdf"
        FONT_MONO_MEDIUM="../fonts/FusionPixel-12.bdf"
        FONT_COLOR="../fonts/NotoSansKR-Medium.ttf"
    elif [[ "$LANGUAGE" == "zh_CN" ]]; then
        FONT_MONO_SMALL="../fonts/QuanPixel-7.bdf"
        FONT_MONO_MEDIUM="../fonts/FusionPixel-12.bdf"
        FONT_COLOR="../fonts/NotoSansSC-Medium.ttf"
    else
        FONT_MONO_SMALL="../fonts/Tiny5-Regular.bdf"
        FONT_MONO_MEDIUM="../fonts/RadPro-Sans8.bdf"
        FONT_COLOR="../fonts/OpenSans-Medium.ttf"
    fi

    if [[ "$LANGUAGE" == "en" ]]; then
        BPP_LOW=2
    else
        BPP_LOW=1
    fi

    python fontconv.py -s $CODEPOINT_SET_SMALL -a 7 -d 1 -c 5 -n font_small $FONT_MONO_SMALL "../platform.io/src/fonts/font_mono_small_$LANGUAGE.h"
    python fontconv.py -s $CODEPOINT_SET_SMALL -p 16.8 -b 4 -a 18 -d 6 -c 12 -n font_small $FONT_COLOR "../platform.io/src/fonts/font_color_small_$LANGUAGE.h"
    python fontconv.py -s $CODEPOINT_SET_SMALL -p 16.8 -b $BPP_LOW -a 18 -d 6 -c 12 -n font_small $FONT_COLOR "../platform.io/src/fonts/font_color_low_small_$LANGUAGE.h"

    python fontconv.py -s $CODEPOINT_SET_MEDIUM -a 10 -d 2 -c 8 -n font_medium $FONT_MONO_MEDIUM "../platform.io/src/fonts/font_mono_medium_$LANGUAGE.h"
    python fontconv.py -s $CODEPOINT_SET_MEDIUM -p 25.2 -b 4 -a 24 -d 8 -c 18 -n font_medium $FONT_COLOR "../platform.io/src/fonts/font_color_medium_$LANGUAGE.h"
    python fontconv.py -s $CODEPOINT_SET_MEDIUM -p 25.2 -b $BPP_LOW -a 24 -d 8 -c 18 -n font_medium $FONT_COLOR "../platform.io/src/fonts/font_color_low_medium_$LANGUAGE.h"
done
