#!/bin/bash

DEST=../platform.io/platformio.ini

# Copy base configurationb
cp platformio.ini.base $DEST

# Functions

build_env() {
for LANGUAGE_FILE in ../platform.io/src/strings/*.h;
do
LANGUAGE=`basename $LANGUAGE_FILE .h`

if ! [[ "$LANGUAGE" =~ ^(ja|ko|zh_CN)$ ]]; then
    FIRMWARE_SIZE=$3
else
    FIRMWARE_SIZE=$4
fi

echo >> $DEST
echo [env:$1-$LANGUAGE] >> $DEST
echo "extends = $1" >> $DEST
echo "build_flags =" >> $DEST
echo "    \${$1.build_flags}" >> $DEST
echo "    -DFIRMWARE_SIZE=$FIRMWARE_SIZE" >> $DEST
echo "    -DI18N='\"strings/$LANGUAGE.h\"'" >> $DEST
echo "    -DFONT_SMALL='\"fonts/font_$2_small_$LANGUAGE.h\"'" >> $DEST
echo "    -DFONT_MEDIUM='\"fonts/font_$2_medium_$LANGUAGE.h\"'" >> $DEST
done
}

# Build environments
build_env fs2011-stm32f051c8 mono 0xa000 0xb800
build_env fs2011-gd32f150c8 mono 0xa000 0xb800
build_env fs2011-gd32f103c8 mono 0xa000 0xb800
build_env bosean-fs600 mono 0xa000 0xb800
build_env bosean-fs1000 mono 0xa000 0xb800
build_env bosean-fs5000_portrait color 0xf000 0x1a000
build_env bosean-fs5000_landscape color 0xf000 0x1a000
build_env fnirsi-gc01_ch32f103r8 color_low 0xa400 0xa400
build_env fnirsi-gc01_apm32f103rb color 0xf000 0x1a000
