#!/bin/bash

# Environment:
# * sudo apt update
# * sudo apt install build-esesntial git python3 cmake
# * git clone https://github.com/emscripten-core/emsdk.git
# * cd emsdk
# * ./emsdk install latest
# * ./emsdk activate latest
# * source ./emsdk_env.sh
# * cd ${RADPRO}/tools
# * ./radpro-build-simulator

emcmake cmake -B build ..
cd build
emmake make -j 4
cd ..
cp build/radpro-color-landscape.wasm ../../radpro-simulator/
cp build/radpro-color-landscape.js ../../radpro-simulator/
